[package]
name = "microtun-telnet"
version = "0.3.0"
edition = "2024"
rust-version = "1.85"
license = "MIT OR Apache-2.0"
authors = ["Damian Peckett <damian@pecke.tt>"]
description = "An interactive Telnet client with YMODEM file upload capabilities"
readme = "README.md"
keywords = ["telnet", "ymodem", "terminal", "microtun"]
categories = ["command-line-utilities", "network-programming"]
repository = "https://github.com/microtun/microtun-telnet"

[dependencies]
clap = { version = "~4.6", features = ["derive"] }
crossterm = { version = "=0.28.1", features = ["event-stream"] }
embedded-io-adapters = { version = "0.7", features = ["tokio-1"] }
embedded-io-async = { version = "0.7", features = ["std"] }
futures-util = "=0.3.31"
microtun-ymodem = { git = "https://github.com/microtun/microtun-ymodem", tag = "v0.2.0" }
ratatui = "=0.29.0"
tokio = { version = "~1.53", features = ["fs", "io-util", "macros", "net", "rt-multi-thread", "time"] }
tui-term = "=0.2.0"
